# Generated by Django 5.0.13 on 2025-08-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlanotifications", "0003_keywordforall"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KeywordForAll",
        ),
    ]
