# Generated by Django 5.0.13 on 2025-11-12 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlanotifications', '0004_delete_keywordforall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'verbose_name': 'notification user', 'verbose_name_plural': 'notification users'},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the user accepted the keyword', null=True, verbose_name='accepted at'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The time the object was created.', verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(help_text='Notification keyword', max_length=255, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='latest_notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the last notification was sent at', null=True, verbose_name='latest notification sent at'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='matching_method',
            field=models.CharField(choices=[('WIDE', 'Wide'), ('NARROW', 'Narrow')], default='WIDE', help_text='The matching method for this keyword', max_length=10, verbose_name='matching method'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='notification_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='The frequency of notifications for this keyword', max_length=10, verbose_name='notification frequency'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The time the object was last updated.', verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this keyword', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='parlanotifications.notificationuser', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The time the object was created.', verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='email',
            field=models.EmailField(help_text='email', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='hash',
            field=models.CharField(help_text='Hash for email confirmation', max_length=255, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='latest_notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the last notification was sent at', null=True, verbose_name='latest notification sent at'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The time the object was last updated.', verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for the user', unique=True, verbose_name='uuid'),
        ),
    ]
