apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlasite-x
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - parlameter.si
      secretName: parlasite-x-tls
  rules:
    - host: parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlasite-x
                port:
                  number: 3066
