apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-trbovlje
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/pvc.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  - parladata/cronjobs/task_runner_cronjob.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml

  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parladata-trbovlje
    newTag: 'd9a1c54ea4bedfbb0d6e9e07a294e448552b5ac6'
  - name: parlasolr-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-trbovlje
    newTag: 'd9a1c54ea4bedfbb0d6e9e07a294e448552b5ac6'
  - name: parlacards-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlacards-trbovlje
    newTag: 'd9a1c54ea4bedfbb0d6e9e07a294e448552b5ac6'
  - name: parlasite-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlasite-trbovlje
    newTag: 'd9a1c54ea4bedfbb0d6e9e07a294e448552b5ac6'
  - name: parlassets-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlassets-trbovlje
    newTag: 'd9a1c54ea4bedfbb0d6e9e07a294e448552b5ac6'
