apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-bosna
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/pvc.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  - parladata/cronjobs/task_runner_cronjob.yaml
  - parladata/cronjobs/send_word_notifications.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml
  - parlasite-9/deployment.yaml
  - parlasite-9/ingress.yaml
  - parlasite-9/service.yaml
  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-bosna
    newName: rg.fr-par.scw.cloud/djnd/parladata-bosna
    newTag: '86d08db10007f0d597922c30494569d4fe4218d7'
  - name: parlasolr-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-bosna
    newTag: '86d08db10007f0d597922c30494569d4fe4218d7'
  - name: parlacards-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlacards-bosna
    newTag: '86d08db10007f0d597922c30494569d4fe4218d7'
  - name: parlasite-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlasite-bosna
    newTag: '86d08db10007f0d597922c30494569d4fe4218d7'
  - name: parlassets-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlassets-bosna
    newTag: '86d08db10007f0d597922c30494569d4fe4218d7'
