apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-zagreb
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  # - parladata/cronjobs/task_runner_cronjob.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite-2022/deployment.yaml
  - parlasite-2022/ingress.yaml
  - parlasite-2022/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml

  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-zagreb
    newName: rg.fr-par.scw.cloud/djnd/parladata-zagreb
    newTag: 'b911f65c4b3fa32ac805ca788f8bf63785b7c027'
  - name: parlasolr-zagreb
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-zagreb
    newTag: 'b911f65c4b3fa32ac805ca788f8bf63785b7c027'
  - name: parlacards-zagreb
    newName: rg.fr-par.scw.cloud/djnd/parlacards-zagreb
    newTag: 'b911f65c4b3fa32ac805ca788f8bf63785b7c027'
  - name: parlasite-zagreb
    newName: rg.fr-par.scw.cloud/djnd/parlasite-zagreb
    newTag: 'b911f65c4b3fa32ac805ca788f8bf63785b7c027'
  - name: parlassets-zagreb
    newName: rg.fr-par.scw.cloud/djnd/parlassets-zagreb
    newTag: 'b911f65c4b3fa32ac805ca788f8bf63785b7c027'
