server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  do-not-use-this-index.html;
        add_header "Access-Control-Allow-Origin" "*";
    }

    location = /readyz {
        default_type application/json;
        return 200 '{"ok": true}\n';
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
