apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-ix
  labels:
    app: parlasite-ix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-ix
  template:
    metadata:
      labels:
        app: parlasite-ix
    spec:
      containers:
        - name: parlasite-ix
          image: parlasite-hrvaska
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://files.parlametar.hr"
            - name: PARLASITE_CARDS_URL
              value: "https://kartica.parlametar.hr"
            - name: PARLASITE_DATA_URL
              value: "https://data.parlametar.hr/v3"
            - name: PARLASITE_LEADER_ID
              value: "0"
            - name: PARLASITE_ROOT_ORG_ID
              value: "1067"
            - name: PARLASITE_MANDATE_ID
              value: "13"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: "2020-07-20"
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: "2"
            - name: SENTRY_DSN
              value: https://f7d45d6c90ea4cacb514a111c8c3e310@bugsink.danesjenovdan.si/5
            - name: SENTRY_ENVIRONMENT
              value: hrvaska
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"] # give load balancer time to stop sending traffic to this pod
          startupProbe:
            httpGet:
              path: /readyz
              port: 3066
            periodSeconds: 10
            failureThreshold: 30 # 30x10 = 300s = 5min
