apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlasite-ix
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ix.parlameter.si
      secretName: parlasite-ix-tls
  rules:
    - host: ix.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlasite-ix
                port:
                  number: 3066
