# Generated by Django 5.0.7 on 2024-11-27 11:52

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models

import parladata.models.legislation


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0077_auto_20231110_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=parladata.models.legislation.LegislationStatus.get_or_create_default_photo_pk,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="parladata.legislationstatus",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="classification",
            field=models.TextField(
                blank=True,
                choices=[
                    ("root", "root"),
                    ("pg", "pg"),
                    ("commission", "commission"),
                    ("committee", "committee"),
                    ("council", "council"),
                    ("delegation", "delegation"),
                    ("friendship_group", "friendship_group"),
                    ("investigative_commission", "investigative_commission"),
                    ("other", "other"),
                    ("coalition", "coalition"),
                ],
                help_text="An organization category, e.g. committee",
                null=True,
                verbose_name="classification",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="color",
            field=colorfield.fields.ColorField(
                default="#09a2cc", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="organizationacronym",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationemail",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="parladata.mandate",
                verbose_name="Mandate",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that the member belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_children",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationname",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="personeducation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personeducationlevel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personemail",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personhonorificprefix",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personhonorificsuffix",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personmembership",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="parladata.mandate",
                verbose_name="Mandate",
            ),
        ),
        migrations.AlterField(
            model_name="personmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that the member belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_children",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="personname",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofmandates",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofpoints",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofvoters",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personpreferredpronoun",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personpreviousoccupation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="parladata.person",
            ),
        ),
    ]
