# Generated by Django 5.0.13 on 2025-08-29 13:32

from django.db import migrations


def move_root_org_classification(apps, schema_editor):
    Organization = apps.get_model("parladata", "Organization")
    OrganizationMembership = apps.get_model("parladata", "OrganizationMembership")

    for org in Organization.objects.filter(classification="root"):
        # If the organization has memberships, move the classification to the member org
        memberships = OrganizationMembership.objects.filter(member=org)
        for membership in memberships:
            member_org = membership.organization
            member_org.classification = "root"
            member_org.save()
            # Set the original organization's classification to 'house'
        org.classification = "house"
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "parladata",
            "0078_alter_law_status_alter_organization_classification_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(move_root_org_classification),
    ]
