# Generated by Django 5.0.13 on 2025-11-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0080_alter_agendaitem_options_alter_area_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SessionOrganizationThrough",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "organization",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="session_organization_through",
                                to="parladata.organization",
                            ),
                        ),
                        (
                            "session",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="session_organization_through",
                                to="parladata.session",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "parladata_session_organizations",
                        "unique_together": {("session", "organization")},
                    },
                ),
                migrations.AlterField(
                    model_name="session",
                    name="organizations",
                    field=models.ManyToManyField(
                        help_text="Select the organization(s) that participated in the session.",
                        related_name="sessions",
                        through="parladata.SessionOrganizationThrough",
                        to="parladata.organization",
                        verbose_name="organizations",
                    ),
                ),
            ]
        )
    ]
