# Generated by Django 5.0.13 on 2026-01-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0082_sessionorganizationthrough_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that is a party to the relationship",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to="parladata.organization",
                verbose_name="Child organization",
            ),
        ),
    ]
