# Generated by Django 5.0.13 on 2026-07-29 15:07

from django.db import migrations, models


def set_default_position(apps, schema_editor):
    LegislationStatus = apps.get_model("parladata", "LegislationStatus")
    qs = LegislationStatus.objects.all().order_by("id")
    for i, obj in enumerate(qs, start=1):
        LegislationStatus.objects.filter(pk=obj.pk).update(order=(i * 100))


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0085_alter_organizationmembership_mandate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legislationstatus",
            options={
                "ordering": ["order"],
                "verbose_name": "Legislation status",
                "verbose_name_plural": "Legislation statuses",
            },
        ),
        migrations.AddField(
            model_name="legislationstatus",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Order of legislation status", verbose_name="Order"
            ),
        ),
        migrations.RunPython(set_default_position, migrations.RunPython.noop),
    ]
