# Generated by Django 5.0.13 on 2026-07-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0085_alter_organizationmembership_mandate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmendmentResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The time the object was created.",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The time the object was last updated.",
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Name of the amendment result. For example: 'Accepted', 'Rejected', 'Withdrawn'",
                        null=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amendment result",
                "verbose_name_plural": "Amendment results",
            },
        ),
        migrations.CreateModel(
            name="ProcedureType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The time the object was created.",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The time the object was last updated.",
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Type of procedure (e.g., 'regular', 'urgent', 'short'...)",
                        null=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure type",
                "verbose_name_plural": "Procedure types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Amendment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The time the object was created.",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The time the object was last updated.",
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "uid",
                    models.TextField(
                        blank=True,
                        help_text="uid reference of the amendment found on the source page",
                        null=True,
                        verbose_name="uid",
                    ),
                ),
                (
                    "abbreviation",
                    models.TextField(
                        blank=True,
                        help_text="Abbreviation of the amendment",
                        null=True,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the amendment",
                        null=True,
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "timestamp_vote",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the vote on the amendment",
                        null=True,
                        verbose_name="timestamp vote",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="Insert the title of the amendment eg. 'Amendment on...'",
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "proposer_text",
                    models.TextField(
                        blank=True,
                        help_text="Insert the text of the proposer of the amendment",
                        null=True,
                        verbose_name="proposer text",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Insert the explanation of the amendment",
                        null=True,
                        verbose_name="explanation",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Insert the content of the amendment",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        blank=True,
                        help_text="Insert reference of the amendment",
                        null=True,
                        verbose_name="reference",
                    ),
                ),
                (
                    "legislation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The legislation to which the amendment is proposed",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.law",
                        verbose_name="Legislation",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The motion to which the amendment is proposed",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.motion",
                        verbose_name="Motion",
                    ),
                ),
                (
                    "procedure_phase",
                    models.ForeignKey(
                        blank=True,
                        help_text="The phase of the procedure in which the amendment was proposed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parladata.procedurephase",
                        verbose_name="Procedure phase",
                    ),
                ),
                (
                    "proposed_by_organizations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The organization which proposed the amendment",
                        to="parladata.organization",
                        verbose_name="Proposed by",
                    ),
                ),
                (
                    "proposed_by_people",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The person who proposed the amendment",
                        to="parladata.person",
                        verbose_name="Proposed by",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The type of the procedure in which the amendment was proposed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parladata.proceduretype",
                        verbose_name="Procedure type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amendment",
                "verbose_name_plural": "Amendments",
            },
        ),
    ]
