# Generated by Django 5.0.13 on 2026-07-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0087_amendmentresult_proceduretype_amendment"),
    ]

    operations = [
        migrations.AddField(
            model_name="amendment",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the mandate of the amendment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="parladata.mandate",
                verbose_name="Mandate",
            ),
        ),
    ]
