# Generated by Django 5.0.13 on 2026-08-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0089_amendment_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="procedure_type_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the type of procedure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parladata.proceduretype",
                verbose_name="Procedure type",
            ),
        ),
    ]
