# Generated by Django 5.0.13 on 2026-08-03 16:55

from django.db import migrations


def set_procedure_type_fk(apps, schema_editor):
    Law = apps.get_model("parladata", "Law")
    ProcedureType = apps.get_model("parladata", "ProcedureType")

    procedure_types_by_name = {}
    laws = Law.objects.exclude(procedure_type__isnull=True).exclude(procedure_type="")
    for law in laws.iterator():
        procedure_type = procedure_types_by_name.get(law.procedure_type)
        if procedure_type is None:
            procedure_type, _created = ProcedureType.objects.get_or_create(
                name=law.procedure_type
            )
            procedure_types_by_name[law.procedure_type] = procedure_type
        law.procedure_type_fk = procedure_type
        law.save()


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0090_law_procedure_type_fk"),
    ]

    operations = [
        migrations.RunPython(set_procedure_type_fk),
    ]
