# Generated by Django 5.0.13 on 2026-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0090_auto_20260803_1656"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="law",
            name="procedure_type",
        ),
    ]
