# Generated by Django 5.0.13 on 2026-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0092_remove_law_procedure_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="law",
            old_name="procedure_type_fk",
            new_name="procedure_type",
        ),
    ]
