# Generated by Django 5.0.13 on 2026-08-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0093_rename_procedure_type_fk_law_procedure_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="legislation",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the legislation this link belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="parladata.law",
                verbose_name="Legislation",
            ),
        ),
    ]
