apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-2022
  labels:
    app: parlasite-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-2022
  template:
    metadata:
      labels:
        app: parlasite-2022
    spec:
      containers:
        - name: parlasite-2022
          image: parlasite-zagreb
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://files.zagreb.parlametar.hr"
            - name: PARLASITE_CARDS_URL
              value: "https://kartica.zagreb.parlametar.hr"
            - name: PARLASITE_DATA_URL
              value: "https://data.zagreb.parlametar.hr/v3"
            - name: PARLASITE_LEADER_ID
              value: "79"
            - name: PARLASITE_ROOT_ORG_ID
              value: "1"
            - name: PARLASITE_MANDATE_ID
              value: "1"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: "2025-05-30"
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: ""
            - name: SENTRY_DSN
              value: https://64b10a3bec54dedb44314a61dc68a82b@o1076834.ingest.us.sentry.io/4510062422327296
            - name: SENTRY_ENVIRONMENT
              value: zagreb
