apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-viii
  labels:
    app: parlasite-viii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-viii
  template:
    metadata:
      labels:
        app: parlasite-viii
    spec:
      containers:
        - name: parlasite-viii
          image: parlasite-slovenija-staging
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://parlassets-slovenija-staging.lb.djnd.si"
            - name: PARLASITE_CARDS_URL
              value: "https://parlacards-slovenija-staging.lb.djnd.si"
            - name: PARLASITE_DATA_URL
              value: "https://parladata-slovenija.lb.djnd.si/v3"
            - name: PARLASITE_LEADER_ID
              value: "261"
            - name: PARLASITE_ROOT_ORG_ID
              value: "1"
            - name: PARLASITE_MANDATE_ID
              value: "1"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: "2022-05-11"
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: ""
            - name: SENTRY_DSN
              value: https://64b10a3bec54dedb44314a61dc68a82b@o1076834.ingest.us.sentry.io/4510062422327296
            - name: SENTRY_ENVIRONMENT
              value: slovenija-staging
