apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlacards
  labels:
    app: parlacards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlacards
  template:
    metadata:
      labels:
        app: parlacards
    spec:
      containers:
        - name: parlacards
          image: parlacards-slovenija-staging
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 1000Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 200m
          env:
            - name: VITE_PARLASSETS_URL
              value: https://files.staging.parlameter.si
            - name: VITE_PARLADATA_URL
              value: https://data.staging.parlameter.si/v3
            - name: VITE_PARLACARDS_URL
              value: https://kartica.staging.parlameter.si
            - name: VITE_PARLASITE_URL
              value: https://staging.parlameter.si
            - name: VITE_PARLASITE_URL_BEFORE_2022_05_11
              value: https://viii.parlameter.si
            - name: VITE_PARLASITE_URL_BEFORE_2018-06-20
              value: https://vii.parlameter.si
            - name: VITE_METAIMAGES_URL
              value: https://meta-image-generator.djnd.si/parlameter
            - name: SENTRY_DSN
              value: https://14e0c5a0b2d24367b75f1640b2360814@bugsink.danesjenovdan.si/4
            - name: SENTRY_ENVIRONMENT
              value: slovenija-staging
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          startupProbe:
            httpGet:
              path: /misc/search/?id=0&template=site&locale=sl&no_card_data=true
              port: 3000
            periodSeconds: 10
            failureThreshold: 30 # 30x10 = 300s = 5min
          readinessProbe:
            httpGet:
              path: /misc/search/?id=0&template=site&locale=sl&no_card_data=true
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 60
