apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlacards
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - glej.hrastnik.parlameter.si
        - kartica.hrastnik.parlameter.si
      secretName: parlacards-tls
  rules:
    - host: glej.hrastnik.parlameter.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlacards
                port:
                  number: 3000
    - host: kartica.hrastnik.parlameter.si
      http: *http_paths