apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite
  labels:
    app: parlasite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite
  template:
    metadata:
      labels:
        app: parlasite
    spec:
      containers:
        - name: parlasite
          image: parlasite-hrastnik
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://cdn.hrastnik.parlameter.si"
            - name: PARLASITE_CARDS_URL
              value: "https://glej.hrastnik.parlameter.si"
            - name: PARLASITE_DATA_URL
              value: "https://data.hrastnik.parlameter.si/v3"
            - name: PARLASITE_LEADER_ID
              value: "17"
            - name: PARLASITE_ROOT_ORG_ID
              value: "6"
            - name: PARLASITE_MANDATE_ID
              value: "1"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: "2022-11-29"
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: ""
            - name: SENTRY_DSN
              value: https://64b10a3bec54dedb44314a61dc68a82b@o1076834.ingest.us.sentry.io/4510062422327296
            - name: SENTRY_ENVIRONMENT
              value: hrastnik
