apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite
  labels:
    app: parlasite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite
  template:
    metadata:
      labels:
        app: parlasite
    spec:
      containers:
        - name: parlasite
          image: parlasite-zagreb
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://parlassets-zagreb.lb.djnd.si"
            - name: PARLASITE_CARDS_URL
              value: "https://parlacards-zagreb.lb.djnd.si"
            - name: PARLASITE_DATA_URL
              value: "https://parladata-zagreb.lb.djnd.si/v3"
            - name: PARLASITE_LEADER_ID
              value: "79"
            - name: PARLASITE_ROOT_ORG_ID
              value: "1"
            - name: PARLASITE_MANDATE_ID
              value: "1"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: ""
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: ""
