apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-9
  labels:
    app: parlasite-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-9
  template:
    metadata:
      labels:
        app: parlasite-9
    spec:
      containers:
        - name: parlasite-9
          image: parlasite-bosna
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_CDN_URL
              value: "https://files.ba.parlameter.si"
            - name: PARLASITE_CARDS_URL
              value: "https://kartica.ba.parlameter.si"
            - name: PARLASITE_DATA_URL
              value: "https://data.ba.parlameter.si/v3"
            - name: PARLASITE_LEADER_ID
              value: "0"
            - name: PARLASITE_ROOT_ORG_ID
              value: "33"
            - name: PARLASITE_ROOT_ORG_ID2
              value: "34"
            - name: PARLASITE_MANDATE_ID
              value: "2"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: ""
            - name: PARLASITE_NEWSLETTER_SEGMENT_ID
              value: "3"
            - name: SENTRY_DSN
              value: https://64b10a3bec54dedb44314a61dc68a82b@o1076834.ingest.us.sentry.io/4510062422327296
            - name: SENTRY_ENVIRONMENT
              value: bosna
