# Generated by Django 5.0.13 on 2025-04-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0030_alter_deviationfromgroup_person_and_more"),
        (
            "parladata",
            "0078_alter_law_status_alter_organization_classification_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationVoteDiscord",
            new_name="OrganizationVoteUnity",
        ),
    ]
