# Generated by Django 5.0.13 on 2025-04-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0031_rename_organizationvotediscord_organizationvoteunity"),
        (
            "parladata",
            "0078_alter_law_status_alter_organization_classification_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationvoteunity",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_vote_unities",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationvoteunity",
            name="vote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_vote_unities",
                to="parladata.vote",
            ),
        ),
    ]
