# Generated by Django 5.0.13 on 2025-07-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlacards', '0032_alter_organizationvoteunity_organization_and_more'),
        ('parladata', '0078_alter_law_status_alter_organization_classification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationvoteunity',
            old_name='organization',
            new_name='group',
        ),
    ]
