# Generated by Django 5.0.13 on 2025-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0034_rename_organizationvoteunity_groupunity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviationfromgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="deviationfromgroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupdiscord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupdiscord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupmonthlyvoteattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupmonthlyvoteattendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupnumberofquestions",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupnumberofquestions",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupstylescore",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupstylescore",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="grouptfidf",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="grouptfidf",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupunity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupunity",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvocabularysize",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvocabularysize",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvoteattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvoteattendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvotingdistance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="groupvotingdistance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personavgspeechespersession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personavgspeechespersession",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personmonthlyvoteattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personmonthlyvoteattendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofquestions",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofquestions",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofspokenwords",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofspokenwords",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personstylescore",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personstylescore",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="persontfidf",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="persontfidf",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personvocabularysize",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personvocabularysize",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="personvoteattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="personvoteattendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="sessiongroupattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="sessiongroupattendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="sessiontfidf",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="sessiontfidf",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="votingdistance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="votingdistance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
    ]
