# Generated by Django 5.0.13 on 2026-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlacards', '0035_alter_deviationfromgroup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviationfromgroup',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
