# Generated by Django 5.0.13 on 2026-04-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0036_alter_deviationfromgroup_value"),
        ("parladata", "0083_alter_organizationmembership_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementWithGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The time the object was created.",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The time the object was last updated.",
                        verbose_name="updated_at",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField(null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to="parladata.person",
                    ),
                ),
                (
                    "playing_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="DeviationFromGroup",
        ),
    ]
