# Generated by Django 5.0.13 on 2026-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0037_agreementwithgroup_delete_deviationfromgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personvocabularysize",
            name="person",
        ),
        migrations.RemoveField(
            model_name="personvocabularysize",
            name="playing_field",
        ),
        migrations.DeleteModel(
            name="GroupVocabularySize",
        ),
        migrations.DeleteModel(
            name="PersonVocabularySize",
        ),
    ]
