apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parladata
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - data.trbovlje.parlameter.si
      secretName: parladata-tls
  rules:
    - host: data.trbovlje.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parladata
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parladata-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - files.data.trbovlje.parlameter.si
      secretName: parladata-nginx-tls
  rules:
    - host: files.data.trbovlje.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parladata-nginx
                port:
                  number: 80
