apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parladata-ukrajina
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: parlameter-ukrajina-enable-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - data.ua.parlameter.si
      secretName: parladata-ua-tls
  rules:
    - host: data.ua.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parladata-ukrajina
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parladata-ukrajina-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: parlameter-ukrajina-enable-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - files.data.ua.parlameter.si
      secretName: parladata-ua-nginx-tls
  rules:
    - host: files.data.ua.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parladata-ukrajina-nginx
                port:
                  number: 80
